# Generated by Django 4.0.1 on 2022-01-15 01:16

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='socialPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.BooleanField()),
                ('facebook', models.BooleanField()),
                ('whatsapp', models.BooleanField()),
                ('linkedIn', models.BooleanField()),
                ('twitter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='socialPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=30)),
                ('qrCode', models.EmailField(max_length=254)),
                ('active', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('socialPack', models.CharField(max_length=30)),
            ],
        ),
    ]
