# Generated by Django 4.0.1 on 2022-01-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablaDatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpack',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialpack',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialpack',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='socialpack',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='socialpack',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='socialpackitem',
            name='qrCode',
        ),
        migrations.AddField(
            model_name='socialpack',
            name='socialPack',
            field=models.ManyToManyField(to='tablaDatos.socialPackItem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='socialPack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablaDatos.socialpack'),
        ),
    ]
