# Generated by Django 4.0.1 on 2022-01-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablaDatos', '0002_remove_socialpack_facebook_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='UserData',
        ),
        migrations.AlterField(
            model_name='socialpack',
            name='socialPack',
            field=models.ManyToManyField(to='tablaDatos.SocialPackItem'),
        ),
    ]
