# Generated by Django 4.0.1 on 2022-01-19 19:58

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('tablaDatos', '0003_rename_user_userdata_alter_socialpack_socialpack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='socialPack',
        ),
        migrations.RemoveField(
            model_name='socialpack',
            name='socialPack',
        ),
        migrations.AddField(
            model_name='socialpack',
            name='socialPack',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),      
    ]
